services:
  - type: web
    name: doc-management-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn doc_management.wsgi:application --bind 0.0.0.0:$PORT --workers $WEB_CONCURRENCY --timeout 120 --access-logfile - --error-logfile -"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: "doc-management-backend.onrender.com"
      - key: PORT
        value: 10000
    healthCheckPath: /api/token/
    autoDeploy: true 