services:
  - type: web
    name: doc-management-backend
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn doc_management.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: ".onrender.com" 